<a href="https://colab.research.google.com/github/algoexpert2468/machine-leanrning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## `**data types and attributes**`

In [ ]:
a1=np.array([1,2,3,4,5,6,7,8,9])
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
a1.shape

(9,)

In [ ]:
a2.shape

(2, 3)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [ ]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [ ]:
a1.size,a2.size,a3.size

(9, 6, 18)

In [ ]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

**creating numpy arrays**

In [ ]:
firstarray=np.array([1,2,3,4,5,6,7,8,9])
firstarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
firstarray.dtype

dtype('int64')

In [ ]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random=np.random.randint(0,10,size=(3,3))
random

array([[8, 0, 5],
       [8, 9, 4],
       [8, 0, 7]])

In [ ]:
random1=np.random.rand(5,3)
random1

array([[0.75052089, 0.04892391, 0.65908063],
       [0.18748412, 0.13899273, 0.28471316],
       [0.25547918, 0.40374748, 0.85466913],
       [0.02373047, 0.58613504, 0.69214597],
       [0.30966426, 0.71235842, 0.14713089]])

In [ ]:
np.random.seed(seed=0)
random4=np.random.randint(10,size=(5,3))
random4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
random4.shape

(5, 3)

In [ ]:
np.random.seed(seed=0)
random5=np.random.random((5,3))
random5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## ***viewing arrays and matrix***


In [ ]:
np.unique(random4)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
a1[0],a2[0],a3[0]

(1, array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [ ]:
a3[0][1][2]

6

In [ ]:
a3[:2 , :2 ,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [ ]:
a6=np.random.randint(10,size=(2,3,4,5))
a6

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [ ]:
a6.ndim

4

In [ ]:
a6[:,:,:,:2]

array([[[[9, 4],
         [5, 0],
         [1, 3],
         [0, 1]],

        [[4, 7],
         [2, 0],
         [5, 6],
         [4, 9]],

        [[7, 9],
         [7, 2],
         [9, 4],
         [4, 3]]],


       [[[4, 3],
         [0, 1],
         [0, 5],
         [4, 2]],

        [[0, 7],
         [2, 7],
         [3, 3],
         [1, 2]],

        [[6, 8],
         [0, 6],
         [3, 8],
         [3, 2]]]])

## ***manipulating arrays***

In [ ]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2=np.ones(9)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a1+a2

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a1-a2

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
a1*a2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a1/a2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [ ]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2]])

In [ ]:
a2**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
a2%2

array([[1, 0, 1],
       [0, 1, 0]])

### **agrregation**

In [ ]:
listy=[1,2,3]
type(listy)

list

In [ ]:
sum(listy)

6

In [ ]:
massivea=np.random.random(100000)
massivea.size

100000

In [ ]:
massivea[:10]

array([0.38849579, 0.17518866, 0.07733528, 0.87224364, 0.83140254,
       0.55176048, 0.80888769, 0.11902725, 0.73908009, 0.32196028])

numpysum is faster

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(a2)

3.5

In [ ]:
np.min(a2)

1

In [ ]:
np.max(a2)

6

In [ ]:
np.std(a2)

1.707825127659933

In [ ]:
np.var(a2)

2.9166666666666665

# ***transpose and change the shape of an array***

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2reshape=a2.reshape(2,3,1)
a2reshape*a3

array([[[ 1,  2,  3],
        [ 8, 10, 12],
        [21, 24, 27]],

       [[ 4,  8, 12],
        [20, 25, 30],
        [42, 48, 54]]])

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.T.shape

(3, 2)

In [ ]:
a3.T

array([[[1, 1],
        [4, 4],
        [7, 7]],

       [[2, 2],
        [5, 5],
        [8, 8]],

       [[3, 3],
        [6, 6],
        [9, 9]]])

In [ ]:
a3.T.shape

(3, 3, 2)

***dot product***

In [ ]:
np.random.seed(seed=0)
m1=np.random.randint(10,size=(5,3))
m2=np.random.randint(10,size=(5,3))

In [ ]:
m1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
m2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
m1*m2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
m2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [ ]:
m3=m2.T
m3

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [ ]:
m1.shape

(5, 3)

In [ ]:
m3.shape

(3, 5)

In [ ]:
np.dot(m1,m3)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [ ]:
np.dot(m1,m3).shape

(5, 5)

## ***exercise***

In [139]:
np.random.seed(seed=0)
sales_amount=np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [142]:
weekly_sales=pd.DataFrame(sales_amount,index=["mon","tues","wed","thus","fri"],columns=["peanut","cashew","almond"])
weekly_sales

peanut  cashew  almond
mon       12      15       0
tues       3       3       7
wed        9      19      18
thus       4       6      12
fri        1       6       7

In [146]:
prices=np.array([10,8,5])
prices

array([10,  8,  5])

In [148]:
butter_price=pd.DataFrame(prices.reshape(1,3),index=["prices"],columns=["peanut","cashew","almond"])
butter_price

peanut  cashew  almond
prices      10       8       5

In [150]:
total_sales=prices.dot(sales_amount.T)
total_sales

array([240,  89, 332, 148,  93])

### ***comparision operators***

In [151]:
a1

array([1, 2, 3])

In [152]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [154]:
a2>=a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [155]:
a1==a2

array([[ True,  True,  True],
       [False, False, False]])

# ***sorting arrays***

In [157]:
randomarray=np.random.randint(10,size=(3,5))
randomarray

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [158]:
randomarray.shape

(3, 5)

In [159]:
np.sort(randomarray)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [160]:
np.argsort(randomarray)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [161]:
np.argmin(randomarray)

9

In [162]:
np.argmax(randomarray, axis=0)


array([1, 1, 1, 0, 0])

In [163]:
np.argmax(randomarray, axis=1)

array([4, 1, 1])